### ISSUE TITLE
The description in the wiki render is invalid

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#122] opened 2019-10-29 21:44 UTC
![image](https://user-images.githubusercontent.com/1430603/67811651-8e8e2300-fa9d-11e9-8090-a2e353fa2be5.png)

This causes renders in social media, slack, and other previews to look weird.

**Comment by lsaether** [comment] 2019-10-30 08:48
Will take a look into this, not sure where this is set in docusaurus configuration.

**Comment by lsaether** [comment] 2019-10-30 08:51
What page does this show up on?

**Comment by lsaether** [comment] 2019-10-30 08:53
Should be fixed now. It was caused by placing an image tag on the first line of a docs page. The description is generated by taking the first line of the markdown file for whatever page is being linked. 

Please re-open if you notice the problem again.

**Closed as completed by lsaether** 2019-10-30 08:53 UTC
