### ISSUE TITLE
Prettier and admonitions issue

### ISSUE THREAD

**Issue by emresurmeli** [w3f/polkadot-wiki#3888] opened 2022-10-06 20:26 UTC
Prettier will put the closing `:::` for admonitions at the end of the last line above it if it's on the next line.

Example:

Before prettier:
```
...some text.
:::
```

After prettier:
```
...some text. :::
```

This is not an issue if the closing `:::` is 2 lines below, as such:
```
...some text.

:::
```

Not sure if this can be fixed in the prettier settings, will take a look. But @alfarok if you know off the top of your head, feel free to just close this issue.

**Comment by DrW3RK** [comment] 2022-10-07 09:32
@emresurmeli This is already documented on the Admonitions section of Doscusaurus Wiki I've shared. Looks like that is the expected behaviour https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier

You can close the issue if that section addresses your issue

**Closed as completed** 2022-10-10 20:42 UTC
Labels: P3 - Nice to Have, T0 - Enhancement
