### ISSUE TITLE
Being offline is no longer a slashable offense

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5800] opened 2024-04-19 06:36 UTC
https://wiki.polkadot.network/docs/learn-staking-advanced#unresponsiveness

_For every session, validators will send an "I'm online" heartbeat to indicate they are live. If a validator produces no blocks during an epoch and fails to send the heartbeat, it will be reported as unresponsive. Slashing may occur depending on the repeated offenses and how many other validators were unresponsive or offline during the epoch._

This changes with runtime 1.2.0

_Yes, there's not chilling anymore for being offline since it's no longer a slashable offence. The only punishment is getting less rewards (since offline validators don't participate in consensus/sign statements nor author blocks)._

PR:  https://github.com/polkadot-fellows/runtimes/pull/178

**Comment by Overkillus** [comment] 2024-05-02 13:58
Overlaps with https://github.com/paritytech/polkadot-sdk/issues/4173

ImOnline slashes are indeed no longer present with the 1.2 release.

> Yes, there's not chilling anymore for being offline since it's no longer a slashable offence. The only punishment is getting less rewards (since offline validators don't participate in consensus/sign statements nor author blocks).

Tes and very soon it goes even further. [#2226 ](https://github.com/paritytech/polkadot-sdk/pull/2226) got merged and will release next. With it involuntary chilling will also no longer be caused by slashes/offences. (For more explanations see Disabling Overhaul Summary: https://github.com/paritytech/polkadot-sdk/issues/4359)

**Closed as completed** 2024-05-03 11:23 UTC
Labels: docs
