### ISSUE TITLE
Document difference in block signing between Kusama and Polkadot

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#598] opened 2020-06-23 12:20 UTC
Bruno | W3F
Basti said "Polkadot uses a different algorithm for secondary slots signing." - what does he mean?
Irt kusama vs polkadot
Bill | W3F
hmm, this is the first I've heard of it. where did he say it?
Bruno | W3F
Friday, 10:44am, discussion in Polkadot Validator Lounge on errors in 0.8.11. (btw catching up with stuff in Riot is SUCH a nightmare)
Bill | W3F
holy crap, yes, and trying to find something is like a double-nightmare
Logan
https://matrix.to/#/!NZrbtteFeqYKCUGQtr:matrix.parity.io/$159264274247753LUKac:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=web3.foundation
Bill | W3F
I'm not certain, but I think he might mean the algorithm for secondary slot selection? I remember seeing a PR for this
Logan
Wasn't aware of it either, but there is two secondary slots that can be claimed, a VRF slot and a Plain slot https://github.com/paritytech/substrate/blob/1efa919854649ba33f73059e62a72321306a17f2/client/consensus/babe/src/authorship.rs#L151
Bill | W3F
that's weird, I don't know why a VRF-selected block would be considered secondary.  I thought they were always primary.
Logan
I think it just adds the VRF output to Polkadot secondary blocks

**Comment by lsaether** [comment] 2020-06-23 15:34
Dupe of #597 :stuck_out_tongue:

**Closed as completed** 2020-06-26 09:06 UTC
